[project]
name = "gn-mcp"
version = "0.1.0"
description = "Glassnode API MCP Server"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp[cli]",
    "python-dotenv",
    "glassnode-api @ git+https://github.com/neocortex/glassnode-api.git",
]